"""CLI bridge for MetaOS-governed provider agent sessions.

This command owns governance state. Provider adapters may call it, but they
must not reimplement gate decisions or audit persistence themselves.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

from metaos.core.engine import SEngine
from metaos.core.types import DecisionLevel
from metaos.integrations.agent_runtime.canonical import load_canonical_session
from metaos.integrations.agent_runtime.cli_support import prepare_payload
from metaos.integrations.agent_runtime.contracts import AgentSession, ConfirmationStatus, SessionStatus, high_risk_commit
from metaos.integrations.agent_runtime.provider_context import build_provider_context
from metaos.integrations.agent_runtime.service import AgentRuntimeService


ACCESS_LEVELS = ["owner", "private", "shared", "public"]
MAX_EVIDENCE_BUNDLE_BYTES = 1_000_000


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="metaos-agent", description="MetaOS-governed provider agent sessions")
    parser.add_argument("--data-dir", default="", help="MetaOS DLayer data directory")
    sub = parser.add_subparsers(dest="command", required=True)

    prepare = sub.add_parser("prepare", help="Gate and persist a provider session")
    prepare.add_argument("--session-file", type=Path, required=True, help="AgentSession JSON input")
    prepare.add_argument("--out", type=Path, required=True, help="Prepared AgentSession JSON output")
    prepare.add_argument("--access-level", default="owner", choices=ACCESS_LEVELS)

    context = sub.add_parser("context", help="Read canonical session state and its resolved provider policy")
    context.add_argument("--session-file", type=Path, required=True)

    approve = sub.add_parser("approve", help="Approve a pending yellow-gate session")
    approve.add_argument("--session-file", type=Path, required=True)
    approve.add_argument("--out", type=Path, required=True)
    approve.add_argument("--comment", default="")
    approve.add_argument("--access-level", default="owner", choices=ACCESS_LEVELS)

    reject = sub.add_parser("reject", help="Reject a pending yellow-gate session")
    reject.add_argument("--session-file", type=Path, required=True)
    reject.add_argument("--out", type=Path, required=True)
    reject.add_argument("--comment", default="")
    reject.add_argument("--access-level", default="owner", choices=ACCESS_LEVELS)

    running = sub.add_parser("mark-running", help="Record an actual provider process launch")
    running.add_argument("--session-file", type=Path, required=True)
    running.add_argument("--out", type=Path, required=True)
    running.add_argument("--access-level", default="owner", choices=ACCESS_LEVELS)

    finalize = sub.add_parser("finalize", help="Record an actual provider outcome")
    finalize.add_argument("--session-file", type=Path, required=True, help="Prepared/running AgentSession JSON input")
    finalize.add_argument("--out", type=Path, required=True, help="Final AgentSession JSON output")
    finalize.add_argument("--summary", required=True)
    finalize.add_argument("--evidence", action="append", default=[])
    finalize.add_argument("--evidence-file", type=Path, help="bounded structured evidence JSON generated by an adapter")
    finalize.add_argument("--verification-passed", action="store_true")
    finalize.add_argument("--access-level", default="owner", choices=ACCESS_LEVELS)
    return parser


def _read_session(path: Path) -> AgentSession:
    return AgentSession.from_dict(json.loads(path.read_text(encoding="utf-8")))


def _write_session(path: Path, session: AgentSession) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(session.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _canonical_context(engine: SEngine, submitted: AgentSession) -> tuple[AgentSession, dict]:
    session = load_canonical_session(engine, submitted)
    context = build_provider_context(session, session_asset_path=f"asset:{session.asset_id}")
    return session, prepare_payload(session, context)


def _require_high_risk_confirmation(runtime: AgentRuntimeService, session: AgentSession, access_level: str) -> AgentSession:
    """Elevate every R3/R4 commit to a target-bound confirmation checkpoint.

    A green dynamic Gate means no additional blocker was found. It does not
    replace the explicit, short-lived human authorization required to execute
    an external high-impact target binding.
    """
    if not high_risk_commit(session) or session.status != SessionStatus.PREPARED:
        return session
    session.status = SessionStatus.BLOCKED
    session.gate_decision = DecisionLevel.YELLOW.value
    session.confirmation_status = ConfirmationStatus.PENDING
    suffix = "explicit target-bound human confirmation required before high-risk commit launch"
    session.gate_reason = f"{session.gate_reason}; {suffix}" if session.gate_reason else suffix
    runtime._persist_session_asset(session, access_level)
    decision = runtime._save_decision(session, DecisionLevel.YELLOW, access_level, action="blocked")
    session.decision_id = decision.decision_id
    runtime._persist_session_asset(session, access_level)
    runtime._trace(session, "agent_session_confirmation_required", suffix)
    return session


def _bind_approval(runtime: AgentRuntimeService, session: AgentSession, access_level: str) -> AgentSession:
    """Persist the exact target fingerprint that a human just approved."""
    if high_risk_commit(session):
        if not session.target_binding or session.target_binding.is_expired():
            raise ValueError("High-risk commit target binding is missing, invalid, or expired.")
        session.approved_target_fingerprint = session.target_binding.fingerprint()
        runtime._persist_session_asset(session, access_level)
        runtime._trace(session, "agent_session_target_bound_approval", session.approved_target_fingerprint)
    return session


def _validate_bound_launch(session: AgentSession) -> None:
    if not high_risk_commit(session):
        return
    if not session.target_binding or session.target_binding.is_expired():
        raise ValueError("High-risk commit target binding is missing, invalid, or expired.")
    if session.approved_target_fingerprint != session.target_binding.fingerprint():
        raise ValueError("High-risk commit target differs from the approved target binding.")


def _read_evidence_bundle(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {}
    raw = path.read_bytes()
    if len(raw) > MAX_EVIDENCE_BUNDLE_BYTES:
        raise ValueError("Evidence bundle exceeds the bounded size limit.")
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError("Evidence bundle must be valid JSON.") from exc
    if not isinstance(payload, dict):
        raise ValueError("Evidence bundle must be a JSON object.")
    return {
        "source_path": str(path),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "payload": payload,
    }


def _persist_evidence_bundle(runtime: AgentRuntimeService, session: AgentSession, bundle: dict[str, Any], access_level: str) -> AgentSession:
    if not bundle:
        return session
    session.evidence_bundle = bundle
    runtime._persist_session_asset(session, access_level)
    runtime._trace(session, "agent_session_evidence_bundle", str(bundle.get("sha256", "")))
    return session


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    engine = SEngine(data_dir=args.data_dir)
    runtime = AgentRuntimeService(engine)
    try:
        submitted = _read_session(args.session_file)
        if args.command == "prepare":
            session, context = runtime.prepare(submitted, access_level=args.access_level)
            session = _require_high_risk_confirmation(runtime, session, args.access_level)
            context = build_provider_context(session, session_asset_path=f"asset:{session.asset_id}")
            _write_session(args.out, session)
            print(json.dumps(prepare_payload(session, context), ensure_ascii=False, indent=2))
            return 0 if session.status.value != "blocked" else 3
        if args.command == "context":
            _, payload = _canonical_context(engine, submitted)
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 0

        session = load_canonical_session(engine, submitted)
        if args.command == "approve":
            session = runtime.approve(session, comment=args.comment, access_level=args.access_level)
            session = _bind_approval(runtime, session, args.access_level)
            _write_session(args.out, session)
            print(json.dumps(session.to_dict(), ensure_ascii=False, indent=2))
            return 0
        if args.command == "reject":
            session = runtime.reject(session, comment=args.comment, access_level=args.access_level)
            _write_session(args.out, session)
            print(json.dumps(session.to_dict(), ensure_ascii=False, indent=2))
            return 0
        if args.command == "mark-running":
            _validate_bound_launch(session)
            session = runtime.mark_running(session, access_level=args.access_level)
            _write_session(args.out, session)
            context = build_provider_context(session, session_asset_path=f"asset:{session.asset_id}")
            print(json.dumps(prepare_payload(session, context), ensure_ascii=False, indent=2))
            return 0
        if args.command == "finalize":
            bundle = _read_evidence_bundle(args.evidence_file)
            session = runtime.finalize(
                session,
                summary=args.summary,
                evidence=args.evidence,
                verification_passed=args.verification_passed,
                access_level=args.access_level,
            )
            session = _persist_evidence_bundle(runtime, session, bundle, args.access_level)
            _write_session(args.out, session)
            print(json.dumps(session.to_dict(), ensure_ascii=False, indent=2))
            return 0 if args.verification_passed else 4
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
